import { IconType } from '@/types/icon.type';

const DEFAULT_PATH = '/assets/icons/';

export const ICON_LIST = [
  'logo-stitch',
  'circle-check-off',
  'circle-check',
  'square-check-off',
  'square-check',
  'eye-on',
  'eye-off',
  'mark-red',
  'mark-green',
  'confirm',
  'wiive-logo',
  'chevron',
  'chevron-right',
  'google-logo',
  'kakao-logo',
  'naver-logo',
  'edit-img',
  'upload-failed',
  'hamburger',
  'home',
  'drive',
  'stroke-star',
  'trash',
  'work-sheet',
  'search',
  'plus',
  'list',
  'card',
  'more',
  'more-trash',
  'more-edit',
  'clear',
  'trash-white',
  'star-white',
  'folder-white',
  'all-clear',
  'minus-box',
  'square-white',
  'folder-gray',
  'exclamation-mark',
  'right-arrow',
  'restore',
  'permanent-trash',
  'menu-unstarred',
  'menu-download',
  'folder-add',
  'upload-file',
  'failed-error',
  'reload',
  'uploading',
  'success-upload',
] as const;

export const ICON = ICON_LIST.reduce((acc, item) => {
  acc[item] = `${DEFAULT_PATH}${item}.svg`;
  return acc;
}, {} as IconType);
